apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploy.name}}"
spec:
  selector:
    matchLabels:
      app: service-tracker-ui
  template:
    metadata:
      labels:
        app: service-tracker-ui
    spec:
      containers:
        - image: "{{.Values.deploy.acrServer}}/hackfest/service-tracker-ui:{{.Values.deploy.imageTag}}"
          imagePullPolicy: Always
          name: service-tracker-ui
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"
          env:
            - name: FLIGHT_API_ROOT
              value: http://flights-api:3003/
            - name: WEATHER_API_ROOT
              value: http://weather-api:3015/
            - name: QUAKES_API_ROOT
              value: http://quakes-api:3012/
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: appinsights-aro-demo-appinsights-demo
                  key: instrumentationKey
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
          - containerPort: {{.Values.deploy.containerPort}}
            protocol: TCP
      restartPolicy: Always        